# Generated by Django 5.2.5 on 2025-08-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0004_job_quoterequest_jobupdate_job_quote_request_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticsevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "Customer Created"),
                    ("updated", "Customer Updated"),
                    ("viewed", "Customer Viewed"),
                    ("note_added", "Note Added"),
                    ("file_uploaded", "File Uploaded"),
                    ("email_sent", "Email Sent"),
                    ("call_made", "Call Made"),
                    ("meeting_scheduled", "Meeting Scheduled"),
                    ("task_completed", "Task Completed"),
                    ("quote_duplicated", "Quote Duplicated"),
                ],
                max_length=50,
            ),
        ),
    ]
