# Generated by Django 5.2.5 on 2025-08-23 14:03

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_customer_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=60, unique=True)),
                (
                    "color",
                    models.CharField(
                        default="#0d6efd",
                        help_text="Hex color (e.g. #0d6efd)",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="uniq_tag_name_ci",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="customers", to="customers.tag"
            ),
        ),
    ]
