# Generated by Django 5.2.5 on 2025-08-28 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0004_add_customer_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DuplicateMerge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_taken",
                    models.CharField(
                        choices=[
                            ("merge", "Merge Records"),
                            ("ignore", "Mark as Not Duplicate"),
                            ("delete", "Delete Duplicate"),
                        ],
                        default="merge",
                        help_text="What action was taken with the duplicate",
                        max_length=20,
                    ),
                ),
                (
                    "merged_data",
                    models.JSONField(
                        blank=True,
                        help_text="JSON data showing what fields were merged and from which record",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes about the merge decision"
                    ),
                ),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "duplicate_customer",
                    models.ForeignKey(
                        help_text="The customer record that will be merged/deleted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_merges_as_duplicate",
                        to="customers.customer",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicate_merges_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_customer",
                    models.ForeignKey(
                        help_text="The customer record that will be kept",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_merges_as_primary",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Duplicate Merge",
                "verbose_name_plural": "Duplicate Merges",
                "ordering": ["-performed_at"],
                "unique_together": {("primary_customer", "duplicate_customer")},
            },
        ),
    ]
